# Generated by Django 3.1.2 on 2021-01-24 17:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Intervention_Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('comment', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('update', models.DateTimeField(default=django.utils.timezone.now)),
                ('create', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
