# Generated by Django 3.1.2 on 2021-01-22 14:20

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('a_p_p_l_i_c_a_t_i_o_n_N_a_m_e', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_o_d_e_l_c_o_m_p_o_n_e_n_t',
            name='sensitive_information',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, default='', max_length=200, null=True)),
        ),
    ]
